// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using User.API.Data;

#nullable disable

namespace User.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260515115442_fix domain4")]
    partial class fixdomain4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("User.API.Models.Domain.Permission", b =>
                {
                    b.Property<string>("permissionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("permissionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("permissionId");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            permissionId = "1",
                            permissionName = "Manage Users"
                        },
                        new
                        {
                            permissionId = "2",
                            permissionName = "Manage Reports"
                        },
                        new
                        {
                            permissionId = "3",
                            permissionName = "Manage Invoices"
                        });
                });

            modelBuilder.Entity("User.API.Models.Domain.Role", b =>
                {
                    b.Property<string>("roleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("roleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("roleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            roleId = "1",
                            roleName = "HR Admin"
                        },
                        new
                        {
                            roleId = "2",
                            roleName = "Super Admin"
                        },
                        new
                        {
                            roleId = "3",
                            roleName = "Admin"
                        },
                        new
                        {
                            roleId = "4",
                            roleName = "Employee"
                        });
                });

            modelBuilder.Entity("User.API.Models.Domain.UserPermission", b =>
                {
                    b.Property<string>("permissionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserruserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("isDeletable")
                        .HasColumnType("bit");

                    b.Property<bool>("isReadable")
                        .HasColumnType("bit");

                    b.Property<bool>("isWritable")
                        .HasColumnType("bit");

                    b.HasKey("permissionId");

                    b.HasIndex("UserruserId");

                    b.ToTable("UserPermissions");
                });

            modelBuilder.Entity("User.API.Models.Domain.Userr", b =>
                {
                    b.Property<string>("userId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("roleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("userId");

                    b.HasIndex("roleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("User.API.Models.Domain.UserPermission", b =>
                {
                    b.HasOne("User.API.Models.Domain.Userr", null)
                        .WithMany("UserPermissions")
                        .HasForeignKey("UserruserId");
                });

            modelBuilder.Entity("User.API.Models.Domain.Userr", b =>
                {
                    b.HasOne("User.API.Models.Domain.Role", "role")
                        .WithMany()
                        .HasForeignKey("roleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("role");
                });

            modelBuilder.Entity("User.API.Models.Domain.Userr", b =>
                {
                    b.Navigation("UserPermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
